resolver: lts-15.5
allow-newer: true

packages:
- '.'

# algebraic-graphs and haskell-src-exts are
# unnecessary as extra deps, as those versions
# are included in lts-15.5. They are only listed
# here to be able to build with older ltss (14.27 etc)
extra-deps:
- algebraic-graphs-0.5
- haskell-src-exts-1.22.0
- haskell-src-exts-simple-1.22.0.0
